export type Guide = {
  slug: string;
  title: string;
  description: string;
  category: string;
  readTime: string;
  icon: string;
};

export const guides: Guide[] =
[
  {
    slug: "how-to-start-ai",
    title: "【2026年版】AIツールの始め方ガイド",
    description: "AIツールを使ったことがない初心者向けに、始め方をステップバイステップで解説。おすすめのAIツールも紹介。",
    icon: "🚀",
    category: "初心者向け",
    readTime: "5分",
  },
  {
    slug: "ai-for-business",
    title: "ビジネスで使えるAIツール活用術【業務効率化】",
    description: "メール作成、議事録、プレゼン資料、データ分析...ビジネスの各シーンで使えるAIツールと活用テクニックを紹介。",
    icon: "💼",
    category: "ビジネス",
    readTime: "8分",
  },
  {
    slug: "ai-image-generation",
    title: "【2026年最新】AI画像生成ツール徹底比較｜無料で使えるおすすめ5選",
    description: "Midjourney、DALL-E、Stable Diffusion、Adobe Firefly、Canva AIを徹底比較。料金・特徴・用途別おすすめを解説。",
    icon: "🎨",
    category: "AI画像",
    readTime: "10分",
  },
  {
    slug: "ai-side-business",
    title: "AIツールで副業を始める方法｜月5万円を目指すロードマップ",
    description: "AIツールを活用した副業の始め方を解説。ブログ運営、コンテンツ作成、デザイン、動画編集の具体的なロードマップ。",
    icon: "💰",
    category: "副業",
    readTime: "10分",
  },
  {
    slug: "ai-video-creation",
    title: "【初心者向け】AI動画生成ツールの選び方ガイド",
    description: "Sora、Runway、Pika、Kling、HailuoAIなどの人気AI動画生成ツールを徹底比較。初心者向けに選び方を解説。",
    icon: "🎬",
    category: "AI動画",
    readTime: "8分",
  },
  {
    slug: "chatgpt-vs-claude",
    title: "ChatGPT vs Claude 徹底比較【2026年最新】どっちを使うべき？",
    description: "ChatGPTとClaudeを料金・機能・日本語品質・コーディング力で徹底比較。それぞれの得意分野と用途別おすすめを解説。",
    icon: "🤖",
    category: "比較",
    readTime: "8分",
  },
  {
    slug: "ai-tools-for-students",
    title: "【2026年版】学生向けAIツール活用ガイド｜勉強・レポート・研究に",
    description: "学生が勉強・レポート作成・研究に活用できるAIツールを厳選紹介。無料で使えるおすすめAIツールと効果的な使い方を解説。",
    icon: "🎓",
    category: "学生向け",
    readTime: "7分",
  },
  {
    slug: "best-ai-for-freelance",
    title: "フリーランス必須のAIツール10選｜業務効率化で収入アップ",
    description: "フリーランスの業務効率化に役立つAIツール10選を厳選紹介。文章作成・画像生成・コーディング・会計まで、収入アップにつながるツールと活用法を解説。",
    icon: "💼",
    category: "フリーランス",
    readTime: "10分",
  },
  {
    slug: "ai-blog-writing",
    title: "AIでブログ記事を書く方法｜月5万円稼ぐブログ運営術",
    description: "ChatGPTやClaudeを使ったブログ記事の書き方を徹底解説。ブログ開設から記事執筆、収益化まで月5万円を目指すロードマップ。",
    icon: "📝",
    category: "ブログ運営",
    readTime: "12分",
  },
  {
    slug: "ai-tools-pricing",
    title: "【2026年最新】主要AIツール料金比較一覧｜無料プランまとめ",
    description: "主要AIツールの料金プランを一覧で比較。無料プランの内容、有料プラン料金、おすすめプランをカテゴリ別に徹底解説。",
    icon: "💰",
    category: "料金比較",
    readTime: "10分",
  },
  {
    slug: "ai-english-learning",
    title: "AIで英語学習を効率化する方法｜2026年おすすめツール5選",
    description: "ChatGPTやClaudeを使った英語学習法を徹底解説。英会話練習、英作文添削、TOEIC対策まで、AIを活用した効率的な学習方法を紹介。",
    icon: "🇬🇧",
    category: "英語学習",
    readTime: "10分",
  },
  {
    slug: "best-ai-for-marketing",
    title: "マーケティングに使えるAIツール10選｜SNS運用・広告・分析を効率化",
    description: "マーケティング業務を効率化するAIツールを厳選紹介。SNS運用、広告クリエイティブ作成、データ分析まで、2026年最新のおすすめAIマーケティングツール10選を徹底解説。",
    icon: "📣",
    category: "マーケティング",
    readTime: "10分",
  },
  {
    slug: "ai-for-remote-work",
    title: "リモートワークを効率化するAIツール完全ガイド｜2026年版",
    description: "リモートワーク・テレワークの効率を劇的に上げるAIツールを厳選紹介。会議、文書作成、プロジェクト管理、コミュニケーションをAIで効率化する方法を解説。",
    icon: "🏠",
    category: "リモートワーク",
    readTime: "8分",
  },
  {
    slug: "ai-for-designers",
    title: "デザイナー向けAIツール10選｜イラスト・UI・ロゴ制作を効率化【2026年版】",
    description: "デザイン業務を効率化するAIツールを厳選紹介。イラスト生成、UI/UXデザイン、ロゴ制作、画像編集まで、おすすめAIツール10選を徹底解説。",
    icon: "🎨",
    category: "デザイン",
    readTime: "10分",
  },
  {
    slug: "ai-programming-school",
    title: "【2026年最新】AI時代のプログラミングスクール比較5選｜AIスキルが学べるおすすめスクール",
    description: "AI・機械学習が学べるプログラミングスクール5社を徹底比較。テックアカデミー、DMM WEBCAMP、Aidemy、キカガク、Progateの料金・カリキュラム・転職支援を解説。",
    icon: "🎓",
    category: "スクール比較",
    readTime: "12分",
  },
  {
    slug: "ai-english-tools",
    title: "【2026年最新】AI英語学習ツール比較5選｜ChatGPTからスピーキング練習まで",
    description: "AI活用の英語学習ツール・オンライン英会話5選を徹底比較。ChatGPT、Duolingo、DMM英会話、NativeCamp、スピークバディの料金・AI機能・学習効果を解説。",
    icon: "🇬🇧",
    category: "英語学習",
    readTime: "10分",
  },
  {
    slug: "ai-job-change",
    title: "【2026年最新】AI業界への転職ガイド｜未経験からAIエンジニアになる方法",
    description: "AI業界への転職方法を徹底解説。doda、リクルートエージェント、Green、レバテックキャリア、ビズリーチの5社を比較。未経験からAIエンジニアになるステップも紹介。",
    icon: "💼",
    category: "転職",
    readTime: "12分",
  },
  {
    slug: "ai-investment",
    title: "【2026年最新】AI投資・資産運用サービス比較5選｜ロボアドバイザーおすすめ",
    description: "AIを活用した投資・資産運用サービス5選を徹底比較。WealthNavi、THEO、ROBOPRO、楽ラップ、SBIラップの手数料・最低投資額・運用実績・NISA対応を解説。",
    icon: "📈",
    category: "投資・資産運用",
    readTime: "10分",
  },
  {
    slug: "ai-for-healthcare",
    title: "AI医療・健康管理ガイド【2026年版】ヘルスケアAI活用術",
    description: "症状チェック、メンタルヘルス、健康データ分析、栄養管理など、医療・健康管理分野でのAIツール活用法を紹介。",
    icon: "🏥",
    category: "ヘルスケア",
    readTime: "10分",
  },
  {
    slug: "ai-music-creation",
    title: "AI音楽制作ガイド【2026年版】初心者でもAIで作曲・編曲",
    description: "Suno、Udio、Soundraw、ElevenLabsなど、おすすめAI音楽ツールの比較と具体的な活用法。BGM制作からボーカル生成まで。",
    icon: "🎵",
    category: "音楽制作",
    readTime: "10分",
  },
  {
    slug: "ai-for-education",
    title: "AI教育活用ガイド【2026年版】教師・学校向けAIツール活用術",
    description: "授業準備、教材作成、成績管理、個別指導、保護者対応など、教育現場でのAIツール活用法を教師・学校関係者向けに解説。",
    icon: "🏫",
    category: "教育",
    readTime: "10分",
  },
  {
    slug: "ai-customer-service",
    title: "AIカスタマーサービス活用ガイド【2026年版】顧客対応を効率化",
    description: "問い合わせ対応、FAQ作成、顧客分析、多言語サポートなど、カスタマーサービス業務でのAI活用法を解説。",
    icon: "🎧",
    category: "カスタマーサービス",
    readTime: "10分",
  },
  {
    slug: "ai-data-analysis",
    title: "AIデータ分析ガイド【2026年版】ノーコードでデータ分析を効率化",
    description: "Excel分析、可視化、レポート作成、予測分析まで、プログラミング不要で使えるAIデータ分析ツールと活用法を紹介。",
    icon: "📊",
    category: "データ分析",
    readTime: "10分",
  },
  {
    slug: "ai-meeting-notes",
    title: "AI議事録ツール比較ガイド【2026年版】会議の文字起こしを自動化",
    description: "会議の文字起こし、要約、タスク抽出、多言語対応など、議事録作成を自動化するおすすめAI議事録ツールと活用法を紹介。",
    icon: "🎙️",
    category: "議事録",
    readTime: "10分",
  },
  {
    slug: "ai-presentation",
    title: "AIプレゼン資料作成ガイド【2026年版】スライド作成を自動化",
    description: "構成案、スライド生成、図解、原稿作成まで、プレゼン資料作成を効率化するおすすめAIツールと活用術を紹介。",
    icon: "📽️",
    category: "プレゼン",
    readTime: "10分",
  },
  {
    slug: "ai-translation",
    title: "AI翻訳ツール比較ガイド【2026年版】高精度な多言語翻訳",
    description: "ビジネス文書、メール、Webサイト、論文翻訳まで、用途別おすすめAI翻訳ツールと高精度に翻訳するコツを紹介。",
    icon: "🌐",
    category: "翻訳",
    readTime: "10分",
  },
  {
    slug: "ai-photo-editing",
    title: "AI画像編集ツール比較ガイド【2026年版】写真加工を自動化",
    description: "背景削除、画質向上、不要物消去、自動補正など、写真加工を効率化するおすすめAI画像編集ツールと活用法を紹介。",
    icon: "🖼️",
    category: "画像編集",
    readTime: "10分",
  },
  {
    slug: "ai-coding-assistant",
    title: "AIコーディングアシスタント比較ガイド【2026年版】開発を高速化",
    description: "コード生成、レビュー、デバッグ、リファクタリング、テスト作成まで、開発効率を劇的に上げるAIコーディングアシスタントと活用法を紹介。",
    icon: "⌨️",
    category: "コーディング",
    readTime: "10分",
  },
  {
    slug: "ai-email-writing",
    title: "AIメール作成ツール比較ガイド【2026年版】ビジネスメールを自動化",
    description: "ビジネスメール、営業メール、英文メール、返信文作成など、メール業務を効率化するおすすめAIメール作成ツールと活用法を紹介。",
    icon: "✉️",
    category: "メール作成",
    readTime: "10分",
  },
  {
    slug: "ai-transcription",
    title: "AI音声文字起こしツール比較ガイド【2026年版】会議・インタビューを自動化",
    description: "会議録、インタビュー、講義、動画字幕など、音声のテキスト化を自動化するおすすめAI文字起こしツールと活用法を紹介。",
    icon: "🎤",
    category: "文字起こし",
    readTime: "10分",
  },
  {
    slug: "ai-slide-creation",
    title: "AIスライド作成ツール比較ガイド【2026年版】プレゼン資料を自動生成",
    description: "スライドの自動生成、構成設計、図解、原稿作成など、プレゼン資料制作を効率化するおすすめAIスライド作成ツールと活用法を紹介。",
    icon: "🪄",
    category: "スライド作成",
    readTime: "10分",
  },
  {
    slug: "ai-summary",
    title: "AI要約ツール比較ガイド【2026年版】長文記事・論文を瞬時に要約",
    description: "長文記事、論文、会議録、書籍、動画など、あらゆるコンテンツを瞬時に要約できるおすすめAI要約ツールと活用法を紹介。",
    icon: "📑",
    category: "要約",
    readTime: "10分",
  },
  {
    slug: "ai-logo-creation",
    title: "AIロゴ作成ツール比較ガイド【2026年版】無料で高品質ロゴをAI生成",
    description: "ブランドロゴ、サービスロゴ、SNSアイコンまで、無料で使えるおすすめAIロゴ生成ツールと活用法を紹介。",
    icon: "🏷️",
    category: "ロゴ作成",
    readTime: "10分",
  },
  {
    slug: "ai-chatbot-creation",
    title: "AIチャットボット作成ガイド【2026年版】ノーコードで自社ボット構築",
    description: "社内FAQ、カスタマーサポート、EC、業務自動化まで、ノーコードでチャットボットを構築するおすすめAIツールと活用法を紹介。",
    icon: "🤖",
    category: "チャットボット",
    readTime: "10分",
  },
  {
    slug: "ai-seo",
    title: "AI SEO対策ガイド【2026年版】検索上位を狙うAIツール活用法",
    description: "キーワード調査、競合分析、記事構成、リライトまで、検索上位を狙うおすすめAI SEOツールと活用法を紹介。",
    icon: "🔍",
    category: "SEO",
    readTime: "10分",
  },
  {
    slug: "ai-resume",
    title: "AI履歴書・職務経歴書作成ガイド【2026年版】転職で差がつく書類作成",
    description: "自己PR、志望動機、職務要約、面接対策までAIで効率化するおすすめAIツールと活用テクニックを紹介。",
    icon: "📄",
    category: "転職書類",
    readTime: "10分",
  },
  {
    slug: "ai-english-proofreading",
    title: "AI英文校正ツール比較ガイド【2026年版】ビジネス英語を自然に添削",
    description: "ビジネスメール、論文、英文レポートを自然で正確に添削するおすすめAI英文校正ツールと活用法を紹介。",
    icon: "📝",
    category: "英文校正",
    readTime: "10分",
  },
  {
    slug: "ai-avatar-creation",
    title: "AIアバター作成ツール比較ガイド【2026年版】動画・SNS用アバターを自動生成",
    description: "動画用バーチャルプレゼンター、SNSアイコン、VTuber向けキャラクターまで、用途別のおすすめAIアバター作成ツールと活用法を紹介。",
    icon: "🧑‍🎤",
    category: "アバター作成",
    readTime: "10分",
  },
  {
    slug: "ai-3d-modeling",
    title: "AI 3Dモデル生成ツール比較ガイド【2026年版】テキストから3Dを自動生成",
    description: "テキスト・画像から3Dモデル生成、ゲーム素材、プロダクトデザイン、メタバース活用まで、おすすめAI 3Dツールと活用法を紹介。",
    icon: "🧊",
    category: "3Dモデル",
    readTime: "10分",
  },
  {
    slug: "ai-background-removal",
    title: "AI背景除去ツール比較ガイド【2026年版】写真の背景を一瞬で透過",
    description: "商品写真、人物写真、SNS素材、ECサイト画像など、用途別おすすめAI背景透過ツールと活用法を紹介。",
    icon: "✂️",
    category: "背景除去",
    readTime: "10分",
  },
  {
    slug: "ai-interior-design",
    title: "AIインテリアデザインツール比較ガイド【2026年版】部屋のコーデを自動提案",
    description: "部屋のレイアウト、家具選び、配色提案、リフォームシミュレーションまで、おすすめAIインテリアツールと活用法を紹介。",
    icon: "🛋️",
    category: "インテリア",
    readTime: "10分",
  },
  {
    slug: "ai-article-rewriting",
    title: "AI記事リライトツール比較ガイド【2026年版】既存記事を高品質に書き直し",
    description: "SEOリライト、口調変更、要約リライト、翻訳リライトなど、用途別おすすめAIリライトツールと活用法を紹介。",
    icon: "🔁",
    category: "記事リライト",
    readTime: "10分",
  },
  {
    slug: "ai-subtitle-creation",
    title: "AI字幕作成ツール比較ガイド【2026年版】動画字幕を自動生成",
    description: "動画音声の文字起こし、多言語翻訳、SRT/VTT出力、ショート動画字幕まで、字幕作成を自動化するおすすめAI字幕ツールと活用法を紹介。",
    icon: "💬",
    category: "字幕作成",
    readTime: "10分",
  },
  {
    slug: "ai-image-upscaling",
    title: "AI画像拡大ツール比較ガイド【2026年版】低解像度画像を高画質化",
    description: "古い写真、商品画像、イラスト、SNSアイコンまで、劣化なく高画質化するおすすめAI画像拡大ツールと活用法を紹介。",
    icon: "🔍",
    category: "画像拡大",
    readTime: "10分",
  },
  {
    slug: "ai-character-generation",
    title: "AIキャラクター生成ツール比較ガイド【2026年版】オリジナルキャラをAIで作成",
    description: "オリジナルキャラ、VTuber、ゲーム素材、ブランドマスコットまで、用途別おすすめAIキャラクター生成ツールと活用法を紹介。",
    icon: "🧝",
    category: "キャラ生成",
    readTime: "10分",
  },
  {
    slug: "ai-recipe",
    title: "AI料理レシピツール比較ガイド【2026年版】冷蔵庫の食材から献立提案",
    description: "冷蔵庫の食材からの献立、栄養バランス、時短レシピ、離乳食まで、料理を効率化するおすすめAIレシピツールと活用法を紹介。",
    icon: "🍳",
    category: "料理・レシピ",
    readTime: "10分",
  },
  {
    slug: "ai-for-seniors",
    title: "シニア向けAI活用ガイド【2026年版】60代70代から始めるAIツール入門",
    description: "シニア世代がAIツールを安心して使い始めるための完全ガイド。ChatGPT・Geminiの基本操作から、健康相談・趣味・家族とのコミュニケーションまで分かりやすく解説。",
    icon: "👴",
    category: "シニア向け",
    readTime: "10分",
  },
  {
    slug: "ai-voice-cloning",
    title: "AI音声クローン比較ガイド【2026年版】自分の声でナレーションを自動生成",
    description: "ElevenLabs、Resemble AI、Murf、PlayHTなど主要AI音声クローンツールを徹底比較。料金・品質・日本語対応・商用利用までを解説。",
    icon: "🗣️",
    category: "音声クローン",
    readTime: "10分",
  },
  {
    slug: "ai-podcast-creation",
    title: "AIポッドキャスト制作ガイド【2026年版】台本から配信まで全自動化",
    description: "AIツールを使ったポッドキャスト制作の完全ガイド。台本作成、音声収録、編集、書き起こし、SNS拡散まで、AIで効率化する手順を解説。",
    icon: "🎙️",
    category: "ポッドキャスト",
    readTime: "11分",
  },
  {
    slug: "ai-for-ecommerce",
    title: "ECサイト向けAI活用ガイド【2026年版】売上を伸ばすAI活用術10選",
    description: "ECサイト・ネットショップ運営者向けにAIツールの活用法を徹底解説。商品説明文の自動生成、画像加工、レビュー分析、接客チャット、需要予測まで紹介。",
    icon: "🛒",
    category: "EC・ネットショップ",
    readTime: "12分",
  },
  {
    slug: "ai-content-moderation",
    title: "AIコンテンツモデレーション完全ガイド【2026年版】UGC運営の安全対策",
    description: "ユーザー投稿（UGC）を扱うサービス運営者向けに、AIコンテンツモデレーションの仕組み・活用法・主要ツール・導入手順を徹底解説。",
    icon: "🛡️",
    category: "モデレーション",
    readTime: "11分",
  },
  {
    slug: "ai-for-real-estate",
    title: "不動産業界向けAI活用ガイド｜2026年おすすめツール7選",
    description: "物件紹介文の自動作成、AI査定、顧客対応自動化まで、不動産業務を効率化するAIツール7選と活用法を徹底解説。",
    icon: "🏠",
    category: "不動産",
    readTime: "11分",
  },
  {
    slug: "ai-for-finance",
    title: "金融業界向けAI活用ガイド｜2026年おすすめツール7選",
    description: "市場分析、レポート作成、リスク評価、コンプライアンスチェックまで、金融業務を効率化するAIツール7選と活用法を解説。",
    icon: "💹",
    category: "金融",
    readTime: "11分",
  },
  {
    slug: "ai-for-legal",
    title: "法律業界向けAI活用ガイド｜2026年おすすめツール7選",
    description: "契約書レビュー、判例リサーチ、書面ドラフト作成まで、弁護士・法務担当者の業務を効率化するAIツール7選と活用法を解説。",
    icon: "⚖️",
    category: "法律",
    readTime: "11分",
  },
  {
    slug: "ai-for-hr",
    title: "人事・採用向けAI活用ガイド｜2026年おすすめツール7選",
    description: "求人原稿、書類選考、面接質問、評価面談、1on1まで、HR業務を効率化するAIツール7選と活用法を徹底解説。",
    icon: "👥",
    category: "人事・採用",
    readTime: "11分",
  },
  {
    slug: "ai-for-sales",
    title: "営業向けAI活用ガイド｜2026年おすすめツール7選",
    description: "リード調査、メール作成、商談メモ、提案書作成まで、営業活動を効率化し成約率を上げるAIツール7選と活用法を解説。",
    icon: "💼",
    category: "営業",
    readTime: "11分",
  },
  {
    slug: "ai-for-writers",
    title: "作家・ライター向けAI活用ガイド｜執筆を加速する7つの使い方",
    description: "小説家・Webライター・コピーライター向けにAIツールの活用法を徹底解説。プロット作成、文章推敲、校正、リサーチ、SNS発信まで執筆業務を効率化。",
    icon: "✍️",
    category: "作家・ライター",
    readTime: "12分",
  },
  {
    slug: "ai-for-youtubers",
    title: "YouTuber・動画クリエイター向けAI活用ガイド｜動画制作を自動化",
    description: "YouTuber・動画クリエイター向けに企画、台本、サムネイル、字幕、編集、SEOまで動画制作を効率化するAIツールの使い方を徹底解説。",
    icon: "🎥",
    category: "YouTuber",
    readTime: "12分",
  },
  {
    slug: "ai-for-teachers",
    title: "教員・講師向けAI活用ガイド｜授業準備と校務を効率化する方法",
    description: "小中高の教員・予備校講師・塾講師向けに、授業準備・教材作成・テスト問題・採点補助・保護者対応までAIで効率化する実践的活用法を解説。",
    icon: "👩‍🏫",
    category: "教員・講師",
    readTime: "12分",
  },
  {
    slug: "ai-for-parents",
    title: "子育て中の親向けAI活用ガイド｜育児・家事・教育をラクにする",
    description: "子育て中の親・共働き家庭向けにAIツール活用法を徹底解説。献立・離乳食・育児相談・宿題サポート・読み聞かせ・家事効率化まで紹介。",
    icon: "👨‍👩‍👧",
    category: "子育て",
    readTime: "12分",
  },
  {
    slug: "ai-prompt-engineering",
    title: "プロンプトエンジニアリング入門｜今日から使える12のテクニック",
    description: "ChatGPT・Claude・GeminiなどAIの回答品質を劇的に上げるプロンプトエンジニアリングの基本と実践テクニックを徹底解説。初心者向け。",
    icon: "🧠",
    category: "スキル",
    readTime: "13分",
  },
  {
    slug: "ai-legal-contracts",
    title: "AI法務・契約書ツールガイド【2026年版】契約レビューを効率化",
    description: "契約書レビュー、リスク検出、ドラフト作成、英文契約チェックなど、法務業務を効率化するAIツールと活用法を紹介。",
    icon: "⚖️",
    category: "法務",
    readTime: "10分",
  },
  {
    slug: "ai-for-bloggers",
    title: "ブロガー向けAI活用ガイド【2026年最新】記事作成・SEO・収益化を加速",
    description: "ブログ運営を効率化するAIツール活用法を徹底解説。記事構成作成・執筆・リライト・SEO対策・画像生成まで実践ノウハウを紹介します。",
    icon: "✍️",
    category: "ブログ運営",
    readTime: "12分",
  },
  {
    slug: "ai-for-small-business",
    title: "中小企業経営者向けAI活用ガイド【2026年最新】業務効率化とDX推進",
    description: "中小企業経営者のためのAI活用ガイド。総務・経理・営業・マーケまで限られたリソースで最大の成果を出す導入ステップを解説。",
    icon: "🏢",
    category: "経営・DX",
    readTime: "12分",
  },
  {
    slug: "ai-for-researchers",
    title: "研究者・大学院生向けAI活用ガイド【2026年最新】論文執筆・文献調査を効率化",
    description: "研究者・大学院生のための実践AI活用ガイド。論文執筆・文献調査・データ分析・英文校正まで研究業務を加速する方法を解説。",
    icon: "🔬",
    category: "研究・学術",
    readTime: "12分",
  },
  {
    slug: "ai-for-students",
    title: "学生の論文・レポート向けAI活用ガイド【2026年最新】評価を下げない正しい使い方",
    description: "大学生・高校生のための論文・レポートAI活用ガイド。構成作り・文献収集・引用・英文校正まで評価を上げる賢い使い方を解説。",
    icon: "🎓",
    category: "学生・教育",
    readTime: "12分",
  },
  {
    slug: "ai-workflow-automation",
    title: "AIワークフロー自動化入門【2026年最新】Zapier・Make・n8n徹底活用",
    description: "AI×ワークフロー自動化の実践入門ガイド。ChatGPT APIとZapier・Make・n8nを連携し繰り返しタスクをゼロから自動化する方法を解説。",
    icon: "⚙️",
    category: "自動化",
    readTime: "13分",
  },
  {
    slug: "ai-for-architects",
    title: "建築家・設計者向けAIおすすめ5選【2026年最新】設計・パース・提案資料を効率化",
    description: "建築設計・意匠・構造・施工管理に活用できるAIを徹底解説。ChatGPT・Claude・Midjourney・Stable Diffusion・Lookxで業務を劇的に効率化する方法を紹介。",
    icon: "🏛️",
    category: "建築・設計",
    readTime: "12分",
  },
  {
    slug: "ai-for-event-planners",
    title: "イベント企画者向けAIおすすめ5選【2026年最新】企画立案から集客まで効率化",
    description: "展示会・セミナー・ウェディングなどイベント企画に活用できるAIを徹底解説。企画書作成・集客・運営を爆速化するおすすめ5ツールを紹介。",
    icon: "🎪",
    category: "イベント企画",
    readTime: "12分",
  },
  {
    slug: "ai-for-musicians",
    title: "ミュージシャン・作曲家向けAIおすすめ5選【2026年最新】作曲・編曲・マスタリングを効率化",
    description: "Suno・Udio・AIVA・LANDR・Claudeで作曲から歌詞、編曲、マスタリング、楽曲分析までを効率化する方法を徹底解説。",
    icon: "🎵",
    category: "音楽制作",
    readTime: "12分",
  },
  {
    slug: "ai-for-photographers",
    title: "フォトグラファー向けAIおすすめ5選【2026年最新】RAW現像・レタッチ・アップスケールを効率化",
    description: "Lightroom AI・Topaz Photo AI・Luminar Neo・Photoshop・Midjourneyでレタッチ・現像・合成を劇的に効率化する方法を紹介。",
    icon: "📸",
    category: "写真・レタッチ",
    readTime: "12分",
  },
  {
    slug: "ai-no-code-tools",
    title: "AI×ノーコードツール活用ガイド【2026年最新】おすすめ5選｜アプリ開発を爆速化",
    description: "Bubble・Glide・Dify・Zapier・Makeを組み合わせ、ChatGPT APIを活用したアプリ・自動化を誰でも実現する方法を徹底解説。",
    icon: "🧩",
    category: "ノーコード",
    readTime: "13分",
  },
  {
    slug: "ai-for-marketers",
    title: "マーケター向けAI活用ガイド【2026年最新】業務効率化おすすめ5選",
    description: "広告運用・SEO・SNS・コンテンツ制作・データ分析まで、マーケター業務をAIで効率化する方法を徹底解説。",
    icon: "📣",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-for-content-creators",
    title: "コンテンツクリエイター向けAI活用ガイド【2026年最新】おすすめ5選",
    description: "YouTube・ブログ・Podcast・SNS・動画編集まで、コンテンツクリエイターの制作プロセスをAIで効率化する方法を徹底解説。",
    icon: "🎥",
    category: "クリエイティブ",
    readTime: "12分",
  },
  {
    slug: "ai-for-startups",
    title: "スタートアップ向けAI活用ガイド【2026年最新】事業立ち上げ効率化おすすめ5選",
    description: "MVP開発・営業・採用・顧客対応・経理まで、スタートアップの事業立ち上げに役立つAIツール5選を徹底解説。",
    icon: "🚀",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-data-visualization",
    title: "AIデータ可視化ツールおすすめ5選【2026年最新】グラフ・ダッシュボードを自動生成",
    description: "ChatGPT・Claude・Tableau AI・Power BI Copilotを使ってデータからグラフ・ダッシュボードを自動生成する方法を徹底解説。",
    icon: "📊",
    category: "ビジネス",
    readTime: "12分",
  },
  {
    slug: "ai-customer-support",
    title: "AIカスタマーサポート構築ガイド【2026年最新】チャットボット・自動応答おすすめ5選",
    description: "AIチャットボット・自動メール返信・ナレッジ検索でカスタマーサポートを効率化する方法を徹底解説。",
    icon: "💬",
    category: "ビジネス",
    readTime: "12分",
  },
  {
    slug: "ai-vs-human",
    title: "AIと人間の比較・使い分け完全ガイド【2026年版】",
    description: "AIと人間それぞれの得意・不得意を整理し、ビジネスや日常の場面でどう使い分けるべきかを解説。AIに任せる仕事・人にしかできない仕事の境界線を明確にします。",
    icon: "🤝",
    category: "基礎",
    readTime: "8分",
  },
  {
    slug: "ai-image-vs-photo",
    title: "AI画像 vs 実写【2026年最新】ビジネス活用比較",
    description: "AI生成画像と実写写真をビジネスシーンでどう使い分けるべきか。コスト・スピード・著作権・ブランド信頼性・SEOまで徹底比較し、最適な選択肢を解説します。",
    icon: "🖼️",
    category: "画像・動画",
    readTime: "9分",
  },
  {
    slug: "ai-pricing-comparison",
    title: "主要AIサービス料金徹底比較【2026年版】",
    description: "ChatGPT・Claude・Gemini・Perplexity・Copilot・Midjourneyなど主要AIサービスの料金プランを2026年最新版で徹底比較。コスパ最強はどれかを解説します。",
    icon: "💰",
    category: "料金",
    readTime: "10分",
  },
  {
    slug: "ai-japanese-tools",
    title: "日本語特化AIツール比較【2026年最新】",
    description: "ELYZA・Sarashina・rinna・PLaMoなど日本語特化AIツール、そしてClaudeやGPT-4oの日本語性能を徹底比較。日本語業務に最適なAIを選ぶための実用ガイド。",
    icon: "🇯🇵",
    category: "日本語",
    readTime: "9分",
  },
  {
    slug: "ai-free-tools",
    title: "完全無料で使えるAIツール厳選【2026年版】10選",
    description: "ChatGPT・Claude・Gemini・Microsoft Copilot・Bingなど、完全無料で使える本格AIツールを厳選。コストをかけずにAIを始めたい人必見です。",
    icon: "🆓",
    category: "無料",
    readTime: "8分",
  },
  {
    slug: "ai-for-game-developers",
    title: "ゲーム開発者向けAIツール完全ガイド｜2026年おすすめ5選",
    description: "ChatGPT・Claude・Midjourney・Suno・Scenarioなど、ゲーム開発に役立つAIツール5選を徹底比較。プログラミング・グラフィック・サウンド・シナリオ制作まで活用法を解説。",
    icon: "🎮",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-3d-printing",
    title: "3DプリントAI活用完全ガイド｜2026年おすすめツール5選",
    description: "3Dプリント向けにモデル生成・スライス最適化・トラブルシュートが可能なAIツール5選を解説。Luma AI・Meshy・3DFY・ChatGPT・Spline AIの活用法を紹介。",
    icon: "🖨️",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-fashion-design",
    title: "ファッションデザインAI完全ガイド｜2026年おすすめツール5選",
    description: "ファッションデザイナー・アパレルブランド向けに最適なAIツール5選を徹底解説。Midjourney・Stable Diffusion・CALA・Vue.aiなどでデザイン制作を効率化。",
    icon: "👗",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-news-generation",
    title: "AIニュース生成・要約完全ガイド｜2026年おすすめツール5選",
    description: "ChatGPT・Claude・Perplexity・Feedly AI・NotebookLMでニュース要約・記事生成を効率化する方法を解説。情報収集の時間を10分の1にする活用法を紹介。",
    icon: "📰",
    category: "情報収集",
    readTime: "12分",
  },
  {
    slug: "ai-fact-checking",
    title: "AIファクトチェック・情報検証完全ガイド｜2026年おすすめツール5選",
    description: "Perplexity・GPTZero・Originality.AI・ChatGPT・Google Fact Check Toolsなど、フェイクニュース対策と情報検証に役立つAIツール5選を徹底解説。",
    icon: "✅",
    category: "情報検証",
    readTime: "12分",
  },
  {
    slug: "ai-for-investors",
    title: "投資家向けAIおすすめ7選【2026年最新】活用ガイド",
    description: "ChatGPT・Claude・Gemini・Perplexityで決算分析・銘柄スクリーニング・市況リサーチを効率化する方法を解説。",
    icon: "📈",
    category: "投資・金融",
    readTime: "12分",
  },
  {
    slug: "ai-for-cooks",
    title: "料理・レシピAIおすすめ7選【2026年最新】徹底比較",
    description: "ChatGPT・Claude・Geminiを使った献立作成、レシピ生成、栄養管理、冷蔵庫の余り食材活用法を解説。",
    icon: "🍳",
    category: "料理・レシピ",
    readTime: "11分",
  },
  {
    slug: "ai-for-fitness",
    title: "フィットネス・トレーニングAIおすすめ7選【2026年最新】",
    description: "AIをパーソナルトレーナー代わりに活用してメニュー作成・進捗管理・栄養相談を行う方法を解説。",
    icon: "💪",
    category: "健康・トレーニング",
    readTime: "11分",
  },
  {
    slug: "ai-for-mental-health",
    title: "メンタルヘルスAIアプリおすすめ7選【2026年最新】",
    description: "Woebot・Wysa・ChatGPT・ClaudeなどメンタルケアにAIを活用する方法と注意点を解説。",
    icon: "🧘",
    category: "健康・メンタル",
    readTime: "11分",
  },
  {
    slug: "ai-for-japanese-business",
    title: "日本企業のAI導入事例まとめ【2026年最新】",
    description: "製造・金融・小売・人事など業界別の日本企業AI活用パターンと、おすすめツール7選を解説。",
    icon: "🇯🇵",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "chatgpt-claude-gemini-comparison",
    title: "ChatGPT vs Claude vs Gemini 3社徹底比較【2026年最新】どれを選ぶべき？",
    description: "主要AIチャット3社を料金・日本語品質・コーディング力・文脈長・マルチモーダルで徹底比較し、用途別のおすすめを解説。",
    icon: "⚖️",
    category: "比較",
    readTime: "12分",
  },
  {
    slug: "ai-pricing-detailed",
    title: "主要AIツール料金完全比較【2026年最新】ChatGPT・Claude・Codeium・Notion AI他",
    description: "ChatGPT・Claude・Gemini・Codeium・Notion AI・Perplexity など主要AIサービスの料金を完全比較。無料枠、年払い、API料金まで詳しく解説。",
    icon: "💰",
    category: "料金",
    readTime: "13分",
  },
  {
    slug: "chatgpt-image-generation-guide",
    title: "ChatGPTで画像生成する完全ガイド【2026年最新】DALL-E活用術",
    description: "ChatGPTで画像生成する方法・プロンプトのコツ・商用利用・他の画像AIとの比較まで解説。DALL-E統合機能を最大活用。",
    icon: "🎨",
    category: "画像生成",
    readTime: "11分",
  },
  {
    slug: "ai-text-to-speech",
    title: "AIテキスト読み上げツール比較【2026年最新】ElevenLabs・Azure・Google徹底解説",
    description: "AIテキスト読み上げ（TTS）を音声品質・日本語対応・商用ライセンス・料金で徹底比較。YouTubeナレーション・audiobook制作に最適な1つが見つかります。",
    icon: "🗣️",
    category: "音声AI",
    readTime: "12分",
  },
  {
    slug: "ai-speech-to-text",
    title: "AI音声文字起こしツール比較【2026年最新】Whisper・Otter・Notta徹底解説",
    description: "AI音声文字起こしを精度・日本語対応・価格・話者分離で徹底比較。議事録作成・インタビュー・YouTube字幕生成に最適なサービスを解説します。",
    icon: "🎙️",
    category: "音声AI",
    readTime: "12分",
  },
  {
    slug: "ai-search-engines",
    title: "AI検索エンジン比較【2026年最新】Perplexity・You.com・Phind徹底解説",
    description: "AI検索エンジンをPerplexity・You.com・Phind・Arc Search・Braveで徹底比較。従来のGoogle検索との違い、リサーチ・開発者向けの使い分けを解説。",
    icon: "🔍",
    category: "検索AI",
    readTime: "12分",
  },
  {
    slug: "ai-rag-tools",
    title: "RAG構築ツール比較【2026年最新】LangChain・LlamaIndex・Dify徹底解説",
    description: "RAG構築ツールを徹底比較。LangChain・LlamaIndex・Dify・Haystack・Vectaraの特徴、社内ナレッジAI・カスタマーサポートAIの実装方法を解説。",
    icon: "🦜",
    category: "開発・インフラ",
    readTime: "13分",
  },
  {
    slug: "ai-vector-database",
    title: "ベクターデータベース比較【2026年最新】Pinecone・Weaviate・Qdrant徹底解説",
    description: "AI・RAG構築に必須のベクターDBを徹底比較。Pinecone・Weaviate・Qdrant・Milvus・Chromaの特徴・料金・使い分けを解説。",
    icon: "🗄️",
    category: "インフラ",
    readTime: "13分",
  },
  {
    slug: "ai-for-graphic-designers",
    title: "グラフィックデザイナー向けAIツール2026｜業務効率化おすすめ5選",
    description: "ロゴ・バナー・名刺・ポスター制作を効率化するAIツールを徹底比較。Midjourney・Adobe Firefly・Canva AI・Figma AI・ChatGPTを目的別に解説。",
    icon: "🎨",
    category: "デザイン",
    readTime: "12分",
  },
  {
    slug: "ai-for-web-developers",
    title: "Web開発者向けAIツール2026｜コーディング支援おすすめ5選",
    description: "Web開発者がコーディング・デバッグ・ドキュメント作成を効率化できるAIツールを徹底比較。GitHub Copilot・Cursor・Claude Codeの使い分けを解説。",
    icon: "💻",
    category: "コーディング",
    readTime: "12分",
  },
  {
    slug: "ai-for-translators",
    title: "翻訳家・通訳者向けAIツール2026｜業務効率化おすすめ5選",
    description: "プロの翻訳家・通訳者が作業効率を上げるAIツールを徹底解説。DeepL・ChatGPT・Claude・Geminiの併用でスピードと品質を両立。",
    icon: "🌐",
    category: "翻訳",
    readTime: "12分",
  },
  {
    slug: "ai-for-illustrators",
    title: "イラストレーター向けAIツール2026｜制作支援おすすめ5選",
    description: "イラストレーターの制作を支援するAIツール。Midjourney・NovelAI・Stable Diffusion・Clip Studio・Adobe Fireflyを工程別に解説。",
    icon: "🖌️",
    category: "画像生成",
    readTime: "12分",
  },
  {
    slug: "ai-character-design",
    title: "キャラクターデザイン特化AI2026｜おすすめ5選＆活用術",
    description: "オリジナルキャラ制作に特化したAIツールを徹底比較。NovelAI・Midjourney・Stable Diffusion・Leonardoをキャラ設定から三面図まで解説。",
    icon: "👤",
    category: "キャラ生成",
    readTime: "12分",
  },
  {
    slug: "ai-for-data-scientists",
    title: "データサイエンティスト向けAIおすすめ5選【2026年最新】",
    description: "データサイエンティストのためのAIツールを徹底比較。ChatGPT・Claude・Gemini・GitHub Copilot・Hugging Faceを使った分析・特徴量エンジニアリング・モデル評価の実務活用法を解説。",
    icon: "📊",
    category: "エンジニア",
    readTime: "12分",
  },
  {
    slug: "ai-for-engineers",
    title: "エンジニア向けAI開発支援おすすめ5選【2026年最新】",
    description: "ソフトウェアエンジニア向けAI開発支援ツールを徹底比較。GitHub Copilot・Cursor・Claude Code・ChatGPT・Tabnineのコード補完・レビュー・テスト自動化を解説。",
    icon: "🧑‍💻",
    category: "エンジニア",
    readTime: "12分",
  },
  {
    slug: "ai-prompt-templates",
    title: "プロンプトテンプレート集2026｜実用プロンプト30選",
    description: "仕事・学習・クリエイティブで使えるプロンプトテンプレートを用途別に30個紹介。ChatGPT・Claude・Geminiで即使える実践例と、自作テンプレートの作り方を解説。",
    icon: "📋",
    category: "スキル",
    readTime: "15分",
  },
  {
    slug: "ai-for-product-managers",
    title: "プロダクトマネージャー向けAIおすすめ5選【2026年最新】",
    description: "PMのためのAIツールを徹底比較。ChatGPT・Claude・Notion AI・Gemini・Perplexityを使った要件定義・ユーザーリサーチ・PRD作成・競合分析の実務活用法を解説。",
    icon: "📈",
    category: "ビジネス",
    readTime: "12分",
  },
  {
    slug: "ai-for-qa-testers",
    title: "QA・テスト向けAIおすすめ5選【2026年最新】",
    description: "QAエンジニア・テスターのためのAIツールを徹底比較。ChatGPT・Claude・Testim・Mabl・AutifyでテストケースAI自動生成、E2E自動化、バグ検出を効率化。",
    icon: "🧪",
    category: "エンジニア",
    readTime: "12分",
  },
  {
    slug: "ai-for-elderly-care",
    title: "介護・高齢者ケアAIおすすめ5選【2026年最新】",
    description: "介護現場と家庭の高齢者ケアで活躍するAIツールを徹底比較。見守りカメラ・記録自動化・会話ロボット・服薬管理・音声アシスタントまで、在宅介護から施設運営まで役立つ最新AIを解説します。",
    icon: "🧓",
    category: "業種別",
    readTime: "10分",
  },
  {
    slug: "ai-for-pets",
    title: "ペット向けAIサービスおすすめ5選【2026年最新】",
    description: "犬・猫などペットのためのAIサービスを徹底解説。AIカメラ見守り、健康モニタリング、鳴き声翻訳、しつけAIチャット、給餌自動化まで、2026年最新のペットテックAIを紹介します。",
    icon: "🐶",
    category: "ライフスタイル",
    readTime: "10分",
  },
  {
    slug: "ai-for-childcare",
    title: "育児・子育てAIアプリおすすめ5選【2026年最新】",
    description: "離乳食・睡眠・学習・絵本読み聞かせ・育児相談まで、パパママの味方となる2026年最新AIアプリを分野別に紹介します。",
    icon: "👶",
    category: "ライフスタイル",
    readTime: "10分",
  },
  {
    slug: "ai-for-language-learning",
    title: "言語学習AI比較おすすめ5選【2026年最新】",
    description: "中国語・韓国語・フランス語・スペイン語・ドイツ語など英語以外の多言語学習にも対応するAIツールを徹底比較。会話・文法・発音練習の活用法を解説。",
    icon: "🌏",
    category: "学習",
    readTime: "12分",
  },
  {
    slug: "ai-personality-test",
    title: "AI性格診断・心理テストツールおすすめ5選【2026年最新】",
    description: "MBTI・ビッグファイブ・ストレングスファインダー型のAI診断から、ChatGPTで自作する診断プロンプトまで。自己理解とキャリア選択に役立つ性格診断AIを解説。",
    icon: "🧠",
    category: "その他",
    readTime: "10分",
  },
  {
    slug: "ai-for-saas-builders",
    title: "SaaS開発者のためのAIツール活用ガイド｜2026年おすすめ5選",
    description: "個人開発者・スタートアップのSaaS開発に役立つAIツールを徹底比較。コーディング支援・ドキュメント生成・カスタマーサポート自動化まで、立ち上げを加速する実践ガイド。",
    icon: "🛠️",
    category: "開発者",
    readTime: "12分",
  },
  {
    slug: "ai-api-comparison",
    title: "OpenAI API vs Claude API vs Gemini API 徹底比較【2026年最新】",
    description: "OpenAI・Anthropic・Googleの主要LLM APIを料金・速度・コンテキスト長・機能で徹底比較。アプリ組み込みに最適なAPIの選び方を開発者向けに解説します。",
    icon: "🔌",
    category: "開発者",
    readTime: "13分",
  },
  {
    slug: "ai-llm-self-hosted",
    title: "セルフホスティング可能なオープンソースLLM比較【2026年最新】",
    description: "Llama 3・Mistral・Gemma・Qwen・DeepSeekなどセルフホスト可能なオープンソースLLMをライセンス・性能・GPU要件で徹底比較します。",
    icon: "🦙",
    category: "開発者",
    readTime: "14分",
  },
  {
    slug: "ai-for-non-engineers",
    title: "非エンジニア向けAI活用ガイド｜2026年版",
    description: "プログラミング不要で使えるAIツールと活用法を非エンジニア向けに徹底解説。資料作成・データ集計・メール作成・議事録まで業務効率を一気に高めます。",
    icon: "🧑‍💼",
    category: "ビジネス",
    readTime: "12分",
  },
  {
    slug: "ai-for-managers",
    title: "マネージャー向けAI活用ガイド｜意思決定とチーム運営を加速",
    description: "管理職・マネージャー向けにAIツールの活用法を徹底解説。意思決定支援・1on1準備・評価面談・KPI分析・部下育成までマネジメント業務を効率化します。",
    icon: "👔",
    category: "ビジネス",
    readTime: "13分",
  },
  {
    slug: "ai-text-summarizer",
    title: "AIテキスト要約ツール比較5選【2026年最新】｜長文を瞬時に要約",
    description: "ChatGPT・Claude・Gemini・Notion AI・Perplexityのテキスト要約機能を徹底比較。長文記事・論文・議事録の要約に最適なAIツールを解説。",
    icon: "📰",
    category: "チャット・文章",
    readTime: "12分",
  },
  {
    slug: "ai-pdf-tools",
    title: "AI PDF処理ツール比較5選【2026年最新】｜要約・翻訳・質問応答",
    description: "ChatPDF・Claude・ChatGPT・Adobe Acrobat AI Assistant・Humata AIのPDF処理機能を徹底比較。PDFの要約・翻訳・質問応答・データ抽出に最適なツール。",
    icon: "📄",
    category: "ビジネス",
    readTime: "12分",
  },
  {
    slug: "ai-spreadsheet-tools",
    title: "AIスプレッドシート/Excel拡張ツール比較5選【2026年最新】",
    description: "Microsoft Copilot・Google Workspace Gemini・GPTExcel・SheetAI・Rows AIを徹底比較。Excel/スプレッドシートの数式生成・データ分析・可視化を自動化。",
    icon: "📊",
    category: "ビジネス",
    readTime: "12分",
  },
  {
    slug: "ai-document-generation",
    title: "AIドキュメント生成ツール比較5選【2026年最新】",
    description: "ChatGPT・Claude・Gemini・Notion AI・Microsoft Copilotの文書生成機能を徹底比較。提案書・報告書・マニュアル・議事録を秒で作る方法を解説。",
    icon: "📝",
    category: "ビジネス",
    readTime: "13分",
  },
  {
    slug: "ai-knowledge-base",
    title: "AIナレッジベース構築ツール比較5選【2026年最新】",
    description: "Notion AI・Guru・Glean・NotebookLM・Claude Projectsを徹底比較。社内ドキュメント・マニュアル・FAQを賢く検索できるAIナレッジベースの選び方を解説。",
    icon: "🗄️",
    category: "ビジネス",
    readTime: "13分",
  },
  {
    slug: "ai-for-podcasting",
    title: "ポッドキャスト制作AIおすすめ5選【2026年最新】台本から編集まで自動化",
    description: "台本作成・音声生成・ノイズ除去・書き起こし・配信までポッドキャスト制作を効率化するAIツールを徹底比較。初心者でも番組が作れる手順を解説します。",
    icon: "🎙️",
    category: "音声・音楽",
    readTime: "12分",
  },
  {
    slug: "ai-for-twitch-streamers",
    title: "配信者向けAIおすすめ5選【2026年最新】Twitch・YouTube Liveを盛り上げる",
    description: "モデレーション・翻訳・クリップ生成・視聴者エンゲージメントを高めるAIツールを徹底解説。Twitch・YouTube Liveで活躍する5ツールを紹介。",
    icon: "🎮",
    category: "クリエイティブ",
    readTime: "12分",
  },
  {
    slug: "ai-for-instagram",
    title: "Instagram運用AIおすすめ5選【2026年最新】フォロワー獲得とエンゲージ改善",
    description: "Instagramの投稿・キャプション・ハッシュタグ・リール編集・分析をAIで効率化する方法を解説。フォロワー獲得とエンゲージメント改善に直結する5ツールを紹介。",
    icon: "📸",
    category: "クリエイティブ",
    readTime: "12分",
  },
  {
    slug: "ai-for-tiktok",
    title: "TikTok運用AIおすすめ5選【2026年最新】バズるショート動画を量産",
    description: "TikTokでバズる動画を量産するためのAIツールを厳選。台本・編集・字幕・サムネ・分析まで、AIを使った運用の時短テクを解説します。",
    icon: "🎵",
    category: "クリエイティブ",
    readTime: "12分",
  },
  {
    slug: "ai-content-strategy",
    title: "AIコンテンツ戦略立案ガイド【2026年最新】SEO×SNSで勝つ設計術",
    description: "AIを活用してSEOとSNSの両輪でコンテンツ戦略を設計する方法を徹底解説。キーワード選定・競合分析・カレンダー設計・KPI運用までAI活用の実践ガイド。",
    icon: "🧭",
    category: "ビジネス",
    readTime: "13分",
  },
  {
    slug: "ai-for-japanese-language",
    title: "日本語特化AIツールおすすめ5選【2026年最新】徹底比較｜選び方も解説",
    description: "日本語の敬語・ビジネス文書・翻訳精度に優れた日本語特化AIツールを徹底比較。ChatGPT・Claude・Gemini・ELYZA・Sakana AIの5ツールを用途別に解説します。",
    icon: "🗾",
    category: "言語・翻訳",
    readTime: "12分",
  },
  {
    slug: "ai-multilingual-tools",
    title: "多言語対応AIツールおすすめ5選【2026年最新】徹底比較",
    description: "100言語以上対応のAIツールを徹底比較。ChatGPT・Claude・Gemini・DeepL・Google翻訳の多言語性能・料金・用途別選び方を解説します。",
    icon: "🌐",
    category: "言語・翻訳",
    readTime: "12分",
  },
  {
    slug: "ai-for-translation-business",
    title: "翻訳業界向けAIツールおすすめ5選【2026年最新】プロ翻訳者が使うべきAI",
    description: "翻訳者・翻訳会社向けのAIツールを徹底比較。CAT連携・機械翻訳+ポストエディット・用語管理など、プロの現場で役立つAI活用法を解説します。",
    icon: "🔤",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-for-localization",
    title: "ローカライゼーション向けAIツール5選【2026年最新】L10n業務を効率化",
    description: "アプリ・ゲーム・ソフトウェアのローカライゼーションに使えるAIツールを徹底比較。継続ローカリゼーション・文脈理解・プレースホルダー対応を解説します。",
    icon: "🗺️",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-grammar-check",
    title: "AI文法チェッカー比較おすすめ5選【2026年最新】英文校正ツール徹底解説",
    description: "Grammarly・ProWritingAid・LanguageTool・QuillBot・ChatGPTなどAI文法チェッカーを徹底比較。無料・有料プランの違いと用途別おすすめを解説します。",
    icon: "✍️",
    category: "言語・翻訳",
    readTime: "12分",
  },
  {
    slug: "ai-image-to-video-comparison",
    title: "画像から動画を生成するAI比較5選【2026年最新】Sora/Runway/Pika/Luma/Kling",
    description: "1枚の画像から動画を生成できるAIツール5選を徹底比較。Sora・Runway Gen-3・Pika・Luma Dream Machine・Klingの料金・品質・使いどころを解説。",
    icon: "🎬",
    category: "動画",
    readTime: "12分",
  },
  {
    slug: "ai-meeting-summarizer-comparison",
    title: "AI会議録ツール比較5選【2026年最新】tl;dv/Otter/Notta/Fireflies/Granola",
    description: "Zoom・Teams・Google Meetの会議を自動で文字起こし・要約するAIツール5選を徹底比較。料金・対応言語・連携機能を解説。",
    icon: "📝",
    category: "業務",
    readTime: "12分",
  },
  {
    slug: "ai-ad-creative-comparison",
    title: "AI広告クリエイティブ生成ツール比較5選【2026年最新】",
    description: "広告バナー・コピー・動画クリエイティブをAIで自動生成するツール5選を徹底比較。AdCreative.ai・Canva Magic・Predis・Pencil・Smartlyなど。",
    icon: "📣",
    category: "マーケティング",
    readTime: "12分",
  },
  {
    slug: "ai-recruitment-comparison",
    title: "AI採用ツール比較5選【2026年最新】HireVue/Eightfold/HRBrain/Findy/HRMOS",
    description: "AIを活用した採用支援ツール5選を徹底比較。スカウト・面接・スキルマッチングを自動化し採用成功率を上げる方法を解説。",
    icon: "🧑‍💼",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-trading-tools-comparison",
    title: "AI投資・トレーディング支援ツール比較5選【2026年最新】",
    description: "AIを活用した投資情報・市場分析・自動売買支援ツール5選を徹底比較。Trade Ideas・Tickeron・TrendSpider・Trality・QuantConnectなど。",
    icon: "📈",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-legal-tools-comparison",
    title: "リーガルAIツール比較5選【2026年最新】契約書レビュー・法令検索",
    description: "Harvey AI・LegalForce・LawGeex・Spellbook・MNTSQの法律業務向けAIツール5選を徹底比較。契約書レビューから法令検索まで網羅。",
    icon: "⚖️",
    category: "業種別",
    readTime: "12分",
  },
  {
    slug: "ai-customer-support-comparison",
    title: "AIカスタマーサポートツール比較5選【2026年最新】Intercom/Zendesk/Drift/Ada/Tidio",
    description: "AIで顧客対応を自動化するチャットボット・サポートツール5選を徹底比較。Intercom Fin・Zendesk AI・Drift・Ada・Tidioの料金・機能を解説。",
    icon: "💬",
    category: "業務",
    readTime: "12分",
  },
  {
    slug: "ai-sales-tools-comparison",
    title: "AI営業支援ツール比較5選【2026年最新】Gong/Salesloft/Apollo/Outreach/Clari",
    description: "営業生産性を上げるAIツール5選を徹底比較。Gong・Salesloft・Apollo.io・Outreach・Clariの料金・機能・連携先を解説。",
    icon: "📊",
    category: "業務",
    readTime: "12分",
  },
  {
    slug: "ai-seo-tools-comparison",
    title: "AI SEOツール比較5選【2026年最新】Surfer/Frase/Clearscope/MarketMuse/SE Ranking",
    description: "コンテンツSEOを加速するAIツール5選を徹底比較。Surfer SEO・Frase・Clearscope・MarketMuse・SE Rankingの料金・機能を詳しく解説。",
    icon: "🔍",
    category: "マーケティング",
    readTime: "12分",
  },
  {
    slug: "ai-translation-comparison",
    title: "AI翻訳ツール比較5選【2026年最新】DeepL/Google/ChatGPT/Microsoft/T-3MT",
    description: "ビジネス利用に耐えるAI翻訳ツール5選を徹底比較。DeepL Pro・Google Translate・ChatGPT・Microsoft Translator・T-3MTを精度・料金で解説。",
    icon: "🌐",
    category: "言語・翻訳",
    readTime: "12分",
  },
  {
    slug: "ai-image-generator-comparison-detail",
    title: "AI画像生成ツール詳細比較5選【2026年最新】Midjourney/DALL-E/SD/Imagen/Firefly",
    description: "Midjourney・DALL-E 3・Stable Diffusion・Google Imagen 3・Adobe Fireflyの5大画像生成AIを品質・料金・商用利用で徹底比較。",
    icon: "🎨",
    category: "画像",
    readTime: "12分",
  },
  {
    slug: "ai-voice-cloning-comparison",
    title: "AI音声合成・ボイスクローン比較5選【2026年最新】ElevenLabs/CoeFont/にじボイス",
    description: "ElevenLabs・CoeFont・にじボイス・Murf.ai・Resemble AIの音声合成・ボイスクローンAI5選を徹底比較。商用利用条件と日本語対応を解説。",
    icon: "🎙️",
    category: "音声",
    readTime: "12分",
  },
  {
    slug: "ai-presentation-comparison",
    title: "AIプレゼン作成ツール比較5選【2026年最新】Gamma/Beautiful.ai/Tome/Decktopus/SlidesAI",
    description: "数分でスライドを生成するAIプレゼンツール5選を徹底比較。Gamma・Beautiful.ai・Tome・Decktopus・SlidesAIの料金・テンプレ・連携を解説。",
    icon: "📊",
    category: "業務",
    readTime: "12分",
  },
  {
    slug: "ai-music-creation-comparison",
    title: "AI音楽生成ツール比較5選【2026年最新】Suno/Udio/Stable Audio/Soundraw/AIVA",
    description: "Suno AI・Udio・Stable Audio・Soundraw・AIVAの音楽生成AI5選を徹底比較。歌詞付き楽曲生成から商用BGMまで網羅。",
    icon: "🎵",
    category: "音楽",
    readTime: "12分",
  },
  {
    slug: "ai-no-code-comparison",
    title: "AI×ノーコード開発ツール比較5選【2026年最新】Bolt/v0/Cursor/Replit/Windsurf",
    description: "Bolt.new・v0.dev・Cursor・Replit・Windsurfの最新AIノーコードツール5選を徹底比較。プロンプトで本格Webアプリを構築する方法を解説。",
    icon: "⚡",
    category: "開発",
    readTime: "12分",
  },
  {
    slug: "ai-data-analysis-comparison",
    title: "AIデータ分析ツール比較5選【2026年最新】Julius/Akkio/Tableau/PowerBI/ChatGPT",
    description: "Julius AI・Akkio・Tableau Pulse・Power BI Copilot・ChatGPT Advanced Data Analysisを徹底比較。ノーコードで高度なデータ分析を実現。",
    icon: "📈",
    category: "業務",
    readTime: "12分",
  },
  {
    slug: "ai-search-engines-comparison",
    title: "AI検索エンジン比較5選【2026年最新】Perplexity/Phind/You.com/Bing/Google SGE",
    description: "回答型AI検索エンジン5選を徹底比較。Perplexity・Phind・You.com・Bing Chat・Google SGEの精度・引用・料金を解説。",
    icon: "🔎",
    category: "検索",
    readTime: "12分",
  },
  {
    slug: "ai-rag-platform-comparison",
    title: "AI RAGプラットフォーム比較5選【2026年最新】LangChain/LlamaIndex/Vectara/Pinecone/Weaviate",
    description: "RAG(検索拡張生成)を構築するプラットフォーム5選を徹底比較。LangChain・LlamaIndex・Vectara・Pinecone・Weaviateの特徴を解説。",
    icon: "🧠",
    category: "開発",
    readTime: "12分",
  },
  {
    slug: "ai-llm-api-comparison",
    title: "LLM API比較5選【2026年最新】OpenAI/Anthropic/Google/Mistral/Meta",
    description: "OpenAI GPT・Anthropic Claude・Google Gemini・Mistral・Meta LlamaのLLM APIを料金・性能・コンテキスト長で徹底比較。",
    icon: "🤖",
    category: "開発",
    readTime: "12分",
  },
  {
    slug: "ai-design-tools-comparison",
    title: "AIデザインツール比較5選【2026年最新】Figma AI/Canva Magic/Galileo/Uizard/Visily",
    description: "デザイン作業をAIで加速する5ツールを徹底比較。Figma AI・Canva Magic Studio・Galileo AI・Uizard・Visilyの料金・特徴・連携を解説。",
    icon: "🖌️",
    category: "デザイン",
    readTime: "12分",
  },
  {
    slug: "ai-automation-comparison",
    title: "AIワークフロー自動化ツール比較5選【2026年最新】Zapier/Make/n8n/Pipedream/Workato",
    description: "業務自動化を実現するAIワークフローツール5選を徹底比較。Zapier・Make・n8n・Pipedream・Workatoの料金・連携先・特徴を解説。",
    icon: "⚙️",
    category: "業務",
    readTime: "12分",
  },
];

export const GENRES = [
  "チャット・文章",
  "画像・動画",
  "音声・音楽",
  "ビジネス",
  "クリエイティブ",
  "学習・研究",
  "業種別",
  "その他",
] as const;

export type Genre = (typeof GENRES)[number];

const GENRE_BY_SLUG: Record<string, Genre> = {
  "how-to-start-ai": "その他",
  "chatgpt-vs-claude": "チャット・文章",
  "ai-prompt-engineering": "チャット・文章",
  "ai-summary": "チャット・文章",
  "ai-translation": "チャット・文章",
  "ai-email-writing": "チャット・文章",
  "ai-blog-writing": "チャット・文章",
  "ai-article-rewriting": "チャット・文章",
  "ai-seo": "チャット・文章",
  "ai-resume": "チャット・文章",
  "ai-english-proofreading": "チャット・文章",
  "ai-english-learning": "学習・研究",
  "ai-english-tools": "学習・研究",
  "ai-tools-for-students": "学習・研究",
  "ai-for-students": "学習・研究",
  "ai-for-researchers": "学習・研究",
  "ai-for-education": "学習・研究",

  "ai-image-generation": "画像・動画",
  "ai-photo-editing": "画像・動画",
  "ai-background-removal": "画像・動画",
  "ai-image-upscaling": "画像・動画",
  "ai-character-generation": "画像・動画",
  "ai-avatar-creation": "画像・動画",
  "ai-logo-creation": "画像・動画",
  "ai-3d-modeling": "画像・動画",
  "ai-interior-design": "画像・動画",
  "ai-video-creation": "画像・動画",
  "ai-subtitle-creation": "画像・動画",
  "ai-for-designers": "画像・動画",

  "ai-music-creation": "音声・音楽",
  "ai-voice-cloning": "音声・音楽",
  "ai-transcription": "音声・音楽",
  "ai-podcast-creation": "音声・音楽",

  "ai-for-business": "ビジネス",
  "ai-meeting-notes": "ビジネス",
  "ai-presentation": "ビジネス",
  "ai-slide-creation": "ビジネス",
  "ai-customer-service": "ビジネス",
  "ai-data-analysis": "ビジネス",
  "best-ai-for-marketing": "ビジネス",
  "ai-for-remote-work": "ビジネス",
  "ai-for-sales": "ビジネス",
  "ai-for-hr": "ビジネス",
  "ai-for-small-business": "ビジネス",
  "ai-workflow-automation": "ビジネス",
  "ai-for-architects": "業種別",
  "ai-for-event-planners": "業種別",
  "ai-for-musicians": "クリエイティブ",
  "ai-for-photographers": "クリエイティブ",
  "ai-no-code-tools": "ビジネス",
  "ai-chatbot-creation": "ビジネス",
  "ai-tools-pricing": "ビジネス",
  "ai-side-business": "ビジネス",
  "ai-investment": "ビジネス",
  "ai-job-change": "ビジネス",
  "best-ai-for-freelance": "ビジネス",

  "ai-coding-assistant": "クリエイティブ",
  "ai-programming-school": "学習・研究",
  "ai-for-writers": "クリエイティブ",
  "ai-for-youtubers": "クリエイティブ",
  "ai-for-bloggers": "クリエイティブ",
  "ai-recipe": "クリエイティブ",

  "ai-for-healthcare": "業種別",
  "ai-for-teachers": "業種別",
  "ai-for-parents": "業種別",
  "ai-for-seniors": "業種別",
  "ai-for-real-estate": "業種別",
  "ai-for-finance": "業種別",
  "ai-for-legal": "業種別",
  "ai-legal-contracts": "業種別",
  "ai-for-ecommerce": "業種別",
  "ai-content-moderation": "業種別",
  "ai-for-marketers": "業種別",
  "ai-for-content-creators": "クリエイティブ",
  "ai-for-startups": "業種別",
  "ai-data-visualization": "ビジネス",
  "ai-customer-support": "ビジネス",
  "ai-vs-human": "その他",
  "ai-image-vs-photo": "画像・動画",
  "ai-pricing-comparison": "その他",
  "ai-japanese-tools": "チャット・文章",
  "ai-free-tools": "その他",
  "ai-for-game-developers": "業種別",
  "ai-3d-printing": "業種別",
  "ai-fashion-design": "業種別",
  "ai-news-generation": "その他",
  "ai-fact-checking": "その他",
  "ai-for-investors": "業種別",
  "ai-for-cooks": "その他",
  "ai-for-fitness": "その他",
  "ai-for-mental-health": "その他",
  "ai-for-japanese-business": "業種別",
  "chatgpt-claude-gemini-comparison": "チャット・文章",
  "ai-pricing-detailed": "その他",
  "chatgpt-image-generation-guide": "画像・動画",
  "ai-text-to-speech": "音声・音楽",
  "ai-speech-to-text": "音声・音楽",
  "ai-search-engines": "その他",
  "ai-rag-tools": "その他",
  "ai-vector-database": "その他",

  "ai-for-graphic-designers": "クリエイティブ",
  "ai-for-web-developers": "クリエイティブ",
  "ai-for-translators": "チャット・文章",
  "ai-for-illustrators": "画像・動画",
  "ai-character-design": "画像・動画",

  // 新着: エンジニア・PM向け
  "ai-for-data-scientists": "業種別",
  "ai-for-engineers": "業種別",
  "ai-prompt-templates": "チャット・文章",
  "ai-for-product-managers": "ビジネス",
  "ai-for-qa-testers": "業種別",

  // ライフスタイルAI
  "ai-for-elderly-care": "業種別",
  "ai-for-pets": "その他",
  "ai-for-childcare": "業種別",
  "ai-for-language-learning": "学習・研究",
  "ai-personality-test": "その他",

  "ai-for-saas-builders": "ビジネス",
  "ai-api-comparison": "ビジネス",
  "ai-llm-self-hosted": "ビジネス",
  "ai-for-non-engineers": "ビジネス",
  "ai-for-managers": "ビジネス",
  "ai-text-summarizer": "チャット・文章",
  "ai-pdf-tools": "ビジネス",
  "ai-spreadsheet-tools": "ビジネス",
  "ai-document-generation": "ビジネス",
  "ai-knowledge-base": "ビジネス",

  // 配信・SNS系新規ガイド
  "ai-for-podcasting": "音声・音楽",
  "ai-for-twitch-streamers": "クリエイティブ",
  "ai-for-instagram": "クリエイティブ",
  "ai-for-tiktok": "クリエイティブ",
  "ai-content-strategy": "ビジネス",

  // 言語・翻訳系新規ガイド
  "ai-for-japanese-language": "学習・研究",
  "ai-multilingual-tools": "学習・研究",
  "ai-for-translation-business": "業種別",
  "ai-for-localization": "業種別",
  "ai-grammar-check": "学習・研究",
};

export function genreOf(slug: string): Genre {
  return GENRE_BY_SLUG[slug] ?? "その他";
}

const NEW_COUNT = 8;
export const newSlugs = new Set(guides.slice(-NEW_COUNT).map((g) => g.slug));

export const popularSlugs = new Set([
  "how-to-start-ai",
  "chatgpt-vs-claude",
  "ai-image-generation",
  "ai-blog-writing",
  "ai-side-business",
  "ai-prompt-engineering",
  "ai-for-business",
  "ai-coding-assistant",
]);
